---
# Do some basic sanity checking that things are set up correctly
- name: Test checkstyle
  shell: "source ~/.sdkman/bin/sdkman-init.sh && ~/.local/bin/checkstyle --version"
  args:
    executable: /bin/bash
  changed_when: false

- name: Test detekt
  shell: "source ~/.sdkman/bin/sdkman-init.sh && ~/.local/bin/detekt --version"
  args:
    executable: /bin/bash
  changed_when: false
