---
namespace: elhub
name: devxp-linux
version: "*"
readme: README.md
authors:
  - "@elhub/dev-tools"
description: >
  Ansible script for installing the Linux development environment for Elhub's Development Team.
license:
  - MIT
tags: []
dependencies: {}
repository: https://github.com/elhub/devxp-linux.git
documentation: https://github.com/elhub/devxp-linux/blob/main/README.md
issues: https://jira.elhub.cloud/projects/TD/issues
