---
namespace: elhub
name: dev-tools
version: 1.0-SNAPSHOT
readme: README.md
authors:
  - "@elhub/dev-tools"
description: Ansible script for installing the Linux development environment for Elhub's Dev Team.
license:
  - MIT
tags: []
dependencies: {}
repository: git@github.com:elhub/dev-tools.git
documentation: git@github.com:elhub/dev-tools.git
issues: https://jira.elhub.cloud/projects/TD/issues