---
- name: Deploy devxp-linux
  hosts:
    - localhost
  collections:
    - elhub.wsl
  roles:
    # Install basics
    - role: base
    - role: sdkman
    - role: git
    - role: docker
    - role: molecule
    - role: vault
    # Install SDK
    - role: python
    - role: ansible
    - role: java
    - role: kotlin
    - role: node
    # Install Workflow
    - role: adr
    - role: arcanist
    - role: git_utils
    - role: linters
    - role: github
    # Test
    - role: validate
