---
- name: Ensure clone-all
  template:
    src: git-clone-all.j2
    dest: /usr/local/bin/git-clone-all
    mode: 0755
  become: yes
  ignore_errors: "{{ansible_check_mode}}"

- name: Ensure git-mirror
  template:
    src: git-mirror.j2
    dest: /usr/local/bin/git-mirror
    mode: 0755
  become: yes
  ignore_errors: "{{ansible_check_mode}}"

- name: Ensure make-release
  template:
    src: make-release.j2
    dest: /usr/local/bin/make-release
    mode: 0755
  become: yes
  ignore_errors: "{{ansible_check_mode}}"

- name: Unpack adr-j lib
  unarchive:
    src: "{{repository}}/elhub-bin/adr-j/{{adr_version}}/adr-j.zip"
    dest: /usr/local/lib
    remote_src: yes
  become: yes
  ignore_errors: "{{ansible_check_mode}}"

- name: Link adr
  file:
    src: /usr/local/lib/adr-j-{{adr_version}}/bin/adr-j
    dest: /usr/local/bin/adr
    state: link
  become: yes
  ignore_errors: "{{ansible_check_mode}}"
