---
- name: Install nvm # noqa 303
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  args:
    creates: "{{user_home}}/.nvm/nvm.sh"

- name: Install nodejs # noqa 305
  shell: >
    . {{user_home}}/.nvm/nvm.sh
    nvm install {{nodejs_version}}
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
