---
- name: Install python packages
  apt:
    name:
      - python3
      - python3-pip
  become: yes

- name: Install requirements for python-ldap
  apt:
    name:
      - python3-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
  become: yes

- name: Install python-ldap
  pip:
    name:
      - python-ldap
      - epdb
  become: yes
