- name: Ensure arcanist
  git:
    repo: https://github.com/phacility/arcanist.git
    dest: "{{  install_path  }}/arcanist"
    version: master

- name: Ensure dev-tools-arcanist extensions
  git:
    repo: https://github.com/elhub/dev-tools-arcanist.git
    dest: "{{ install_path }}/extensions"
    version: main

- name: Write arcconfig
  template:
    src: arcconfig.j2
    dest: "{{ install_path }}/config"
    mode: 0644

- name: Link /etc/arcconfig
  file:
    src: "{{ install_path }}/config"
    dest: /etc/arcconfig
    state: link
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Link arc
  file:
    src: "{{ install_path }}/arcanist/bin/arc"
    dest: /usr/local/bin/arc
    state: link
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Link phage
  file:
    src: "{{ install_path }}/arcanist/bin/phage"
    dest: /usr/local/bin/phage
    state: link
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set up arcanist scripts
  template:
    src: "{{ item }}.sh.j2"
    dest: /usr/local/bin/{{ item }}
    mode: 0755
  become_user: root
  become: yes
  loop:
    - arc-init
    - arc-patch-clean
  ignore_errors: "{{ ansible_check_mode }}"

- include_tasks: templates.yml
