---
- name: Ensure checkstyle
  get_url:
    url: https://github.com/checkstyle/checkstyle/releases/download/checkstyle-{{ checkstyle_version }}/checkstyle-{{ checkstyle_version }}-all.jar
    dest: /usr/local/lib/checkstyle.jar
    mode: 0755
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Write checkstyle config
  template:
    src: checkstyle-config.xml.j2
    dest: "{{ lint_config_path }}/checkstyle-config.xml"
    mode: 0644

- name: Create checkstyle script
  template:
    src: checkstyle.sh.j2
    dest: /usr/local/bin/checkstyle
    mode: 0755
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
