---
- name: Ensure detekt
  get_url:
    url: https://github.com/detekt/detekt/releases/download/v{{ detekt_version }}/detekt-cli-{{ detekt_version }}-all.jar
    dest: /usr/local/bin/detekt-cli.jar
    mode: 0755
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Write detekt config
  template:
    src: detekt-config.yml.j2
    dest: "{{ lint_config_path }}/detekt-config.yml"
    mode: 0644

- name: Create detekt script
  template:
    src: detekt.sh.j2
    dest: /usr/local/bin/detekt
    mode: 0755
  become_user: root
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
