---
- name: Ensure install path exists
  file:
    path: "{{ lint_config_path }}"
    state: directory
    mode: 0755

- include_tasks: checkstyle.yml
- include_tasks: detekt.yml
- include_tasks: yamllint.yml
- include_tasks: ansiblelint.yml
